Update ejecutar_script.yml

diff --git a/.github/workflows/ejecutar_script.yml b/.github/workflows/ejecutar_script.yml
--- a/.github/workflows/ejecutar_script.yml
+++ b/.github/workflows/ejecutar_script.yml
@@ -25,6 +25,13 @@ jobs:
       - name: Iniciar conexión WireGuard
         run: sudo wg-quick up wg0
 
+      - name: Verificar conectividad a través de WireGuard
+        run: |
+          if ! timeout 10 dig +short google.com @1.1.1.1 -i wg0; then
+            echo "::error::La conexión WireGuard falló, la clave de podría estar obsoleta."
+            exit 1
+          fi
+
       - name: Configurar Node.js
         uses: actions/setup-node@v4
 
