Update ejecutar_script.yml

diff --git a/.github/workflows/ejecutar_script.yml b/.github/workflows/ejecutar_script.yml
--- a/.github/workflows/ejecutar_script.yml
+++ b/.github/workflows/ejecutar_script.yml
@@ -25,12 +25,15 @@ jobs:
       - name: Iniciar conexión WireGuard
         run: sudo wg-quick up wg0
 
-      - name: Verificar conectividad a través de WireGuard
+      - name: Verificar conexión WireGuard
         run: |
-          if ! timeout 10 dig +short google.com @1.1.1.1 -i wg0; then
-            echo "::error::La conexión WireGuard falló, la clave de podría estar obsoleta."
-            exit 1
-          fi
+          for i in {1..3}; do
+            if timeout 10 curl --silent --interface wg0 --max-time 10 https://google.com> /tmp/wg_ip; then
+              break
+            else
+              sleep 5
+            fi
+          done || (echo "::error::Clave probablemente caducada"; exit 1)
 
       - name: Configurar Node.js
         uses: actions/setup-node@v4
